"""empty message

Revision ID: d4e006cb345e
Revises: 09e2a2a1c419
Create Date: 2019-05-05 17:04:06.510485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e006cb345e'
down_revision = '09e2a2a1c419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('meta_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'meta_tags')
    # ### end Alembic commands ###
