"""empty message

Revision ID: ebd4d53766f4
Revises: 072f22fbca2e
Create Date: 2019-03-01 16:16:59.918702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd4d53766f4'
down_revision = '072f22fbca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photographs', sa.Column('capture_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photographs', sa.Column('location', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photographs', 'location')
    op.drop_column('photographs', 'capture_date')
    # ### end Alembic commands ###
