"""empty message

Revision ID: f563230b7701
Revises: e8c26edc794e
Create Date: 2019-02-20 10:30:38.610891

"""
from alembic import op
import sqlalchemy as sa
from blog import db


# revision identifiers, used by Alembic.
revision = 'f563230b7701'
down_revision = 'e8c26edc794e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))

    # ### commands not auto generated by Alembic ###
    db.engine.execute("UPDATE posts SET published_at = created_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published_at')
    # ### end Alembic commands ###
