KEY_WORDS = [("Adventures", "Adventures"), ("Advertising", "Advertising"), ("Advice", "Advice"), ("Ancient", "Ancient"),
             ("Android", "Android"), ("Anime", "Anime"), ("Apple", "Apple"), ("Architecture", "Architecture"),
             ("Art", "Art"), ("Articles", "Articles"), ("Baking", "Baking"), ("Beauty", "Beauty"), ("Bible", "Bible"),
             ("Big Boyz", "Big Boyz"), ("Blog", "Blog"), ("Blogger", "Blogger"), ("Blogging", "Blogging"),
             ("Book", "Book"), ("Book Reviews", "Book Reviews"), ("Books", "Books"), ("Breaking News", "Breaking News"),
             ("Bulletins", "Bulletins"), ("Business", "Business"), ("Cars", "Cars"), ("Cartoons", "Cartoons"),
             ("Celebrities", "Celebrities"), ("Celebrity", "Celebrity"), ("Children", "Children"), ("Coin", "Coin"),
             ("Comedy", "Comedy"), ("Comics", "Comics"), ("Console", "Console"), ("Cooking", "Cooking"),
             ("Cosmetics", "Cosmetics"), ("Coupons", "Coupons"), ("Crafts", "Crafts"), ("CRM", "CRM"),
             ("Crypto", "Crypto"), ("Cuisine", "Cuisine"), ("Culinary", "Culinary"), ("Culture", "Culture"),
             ("Customer Relationship Management", "Customer Relationship Management"), ("Dating", "Dating"),
             ("Desi", "Desi"), ("Design", "Design"), ("Digital Marketing", "Digital Marketing"), ("Diy", "Diy"),
             ("Dogs", "Dogs"), ("Drawing", "Drawing"), ("Economy", "Economy"), ("Education", "Education"),
             ("Entertainment", "Entertainment"), ("Environment", "Environment"), ("Event", "Event"),
             ("Events", "Events"), ("Exercise", "Exercise"), ("Faith", "Faith"), ("Family", "Family"),
             ("Fantasy", "Fantasy"), ("Fashion", "Fashion"), ("Fat", "Fat"), ("Featured", "Featured"),
             ("Festivities", "Festivities"), ("Fiction", "Fiction"), ("Film", "Film"), ("Finance", "Finance"),
             ("Fitness", "Fitness"), ("Folk", "Folk"), ("Food", "Food"), ("Football", "Football"), ("France", "France"),
             ("Fun", "Fun"), ("Funny", "Funny"), ("Gadgets", "Gadgets"), ("Games", "Games"), ("Gaming", "Gaming"),
             ("Geek", "Geek"), ("Global News", "Global News"), ("God", "God"), ("Google", "Google"),
             ("Google News", "Google News"), ("Gossip", "Gossip"), ("Graphic Design", "Graphic Design"),
             ("Green", "Green"), ("Hacker news", "Hacker news"), ("Headlines", "Headlines"), ("Health", "Health"),
             ("Hip Hop", "Hip Hop"), ("History", "History"), ("Home", "Home"), ("Home Improvement", "Home Improvement"),
             ("Homes", "Homes"), ("Humor", "Humor"), ("Humour", "Humour"), ("Hunting", "Hunting"), ("Ideas", "Ideas"),
             ("Illustration", "Illustration"), ("India", "India"), ("Indie", "Indie"), ("Information", "Information"),
             ("Infuriating", "Infuriating"), ("Inspiration", "Inspiration"), ("Instagram", "Instagram"),
             ("Interesting", "Interesting"), ("Interior Design", "Interior Design"), ("Internet", "Internet"),
             ("Internet Marketing", "Internet Marketing"), ("Iphone", "Iphone"), ("IPO", "IPO"), ("Kids", "Kids"),
             ("Landscape", "Landscape"), ("Latest", "Latest"), ("Latest And Breaking", "Latest And Breaking"),
             ("Latest News", "Latest News"), ("Law", "Law"), ("Leadership", "Leadership"), ("Life", "Life"),
             ("Lifestyle", "Lifestyle"), ("Linux", "Linux"), ("Listen", "Listen"), ("Literature", "Literature"),
             ("Living", "Living"), ("London", "London"), ("Love", "Love"), ("Management", "Management"),
             ("Marketing", "Marketing"), ("Media", "Media"), ("Meme", "Meme"), ("Memes", "Memes"), ("Men", "Men"),
             ("Mental Health", "Mental Health"), ("Microsoft", "Microsoft"), ("Mobile", "Mobile"), ("Money", "Money"),
             ("Movie Reviews", "Movie Reviews"), ("Movies", "Movies"), ("Music", "Music"), ("Nature", "Nature"),
             ("News", "News"), ("News & Views", "News & Views"), ("News Updates", "News Updates"),
             ("Nutrition", "Nutrition"), ("Opinion", "Opinion"), ("Painting", "Painting"), ("Parenting", "Parenting"),
             ("Personal Development", "Personal Development"), ("Pets", "Pets"), ("Philosophy", "Philosophy"),
             ("Photo", "Photo"), ("Photography", "Photography"), ("Photos", "Photos"), ("Pics", "Pics"),
             ("Pictures", "Pictures"), ("Poem", "Poem"), ("Poetry", "Poetry"), ("Politics", "Politics"),
             ("Real Estate", "Real Estate"), ("Recipes", "Recipes"), ("Relationships", "Relationships"),
             ("Religion", "Religion"), ("Retirement", "Retirement"), ("Review", "Review"), ("Reviews", "Reviews"),
             ("Romance", "Romance"), ("Sales", "Sales"), ("Satire", "Satire"), ("Science", "Science"),
             ("SEO", "SEO"), ("Seo", "Seo"), ("Sex", "Sex"), ("Shopping", "Shopping"), ("Soccer", "Soccer"),
             ("Social Media", "Social Media"), ("Software", "Software"), ("Spirituality", "Spirituality"),
             ("Sports", "Sports"), ("Story Time", "Story Time"), ("Tech", "Tech"), ("Technology", "Technology"),
             ("Television", "Television"), ("Thoughts", "Thoughts"), ("Tips", "Tips"), ("Travel", "Travel"),
             ("Trending", "Trending"), ("Tutorials", "Tutorials"), ("Tv", "Tv"), ("Un-categorised", "Un-categorised"),
             ("Vacation", "Vacation"), ("Video", "Video"), ("Videos", "Videos"), ("Web", "Web"),
             ("Web Design", "Web Design"), ("Weight Loss", "Weight Loss"), ("Wellness", "Wellness"),
             ("Wildlife", "Wildlife"), ("Wine", "Wine"), ("Women", "Women"), ("WordPress", "WordPress"),
             ("World", "World"), ("World News", "World News"), ("Writing ", "Writing "), ("YouTube", "YouTube")]

rECAPTCHA_SITE_KEY_V3 = '6LcOf5UUAAAAAOaeMMzkOQm2DpwzLqE54lAgUHHo'
rECAPTCHA_SECRET_V3 = '6LdGf5UUAAAAAFA1wuQWtdaCPQ5sCitoHnGSb6Ch'

rECAPTCHA_SITE_KEY_V2 = '6LdGf5UUAAAAAAaYE0WoNInyJJK7PopHIz3PiYC9'
rECAPTCHA_SECRET_V2 = '6LdGf5UUAAAAAFA1wuQWtdaCPQ5sCitoHnGSb6Ch'
